name: lit_firebase_auth
description: Pre-lit Firebase Authentication. Drop in and add Firebase Auth in just minutes.
repository: https://github.com/funwithflutter/lit_firebase_auth
homepage: https://github.com/funwithflutter/lit_firebase_auth

version: 0.3.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # auth
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.1
  firebase_auth_oauth: ^0.2.1
  # annotation
  meta: ^1.1.8
  freezed_annotation: ^0.11.0+1
  # state
  dartz: ^0.9.1
  provider: ^4.2.0
  state_notifier: ^0.6.0
  flutter_state_notifier: ^0.6.1
  # ui
  flushbar: ^1.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0
  build_runner: ^1.10.0
  freezed: ^0.11.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - graphics/twitter_logo_blue.png
    - graphics/github.png
    - graphics/apple_logo_black.png
    - graphics/apple_logo_white.png
    - graphics/google_logo.png
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
